### ISSUE TITLE
SWITCHdrive download recipe fails

### ISSUE THREAD

**Issue by andreilabin** [autopkg/its-unibas-recipes#74]
Error in com.github.its-unibas.download.switchdrive: Processor: URLDownloader: Error: curl: (8) Weird server reply

**Comment by aschwanb** [comment]
It currently works on my machine. Maybe it was some serverside issue? Could you test again?
```
autopkg run -v com.github.its-unibas.download.switchdrive
```

**Comment by aschwanb** [comment]
I can not reproduce. Feel free to re-open the issue if the problem appears again.
